# Generated by Django 5.2.13 on 2026-04-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeApp', '0002_alter_item_options_order_intent_id_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
