# Generated by Django 5.2.13 on 2026-04-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeApp', '0003_orderitem_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='usd', max_length=10, verbose_name='Currency'),
        ),
    ]
