# Generated by Django 5.2.13 on 2026-04-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeApp', '0006_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
